spring:
  application:
    name: eurekaserver
server:
  port: 8029
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8029/eureka/ # this is the address of Eureka server
  instance:
    prefer-ip-address: true
    appname: eurekaserver
