server:
  port: 8023
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8029/eureka/ # this is the address of Eureka server
  instance:
    appname: loadbalancerservice

spring:
  application:
    name: loadbalancerservice
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 1
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
management:
  endpoints:
    web:
      exposure:
        include: '*'
