server:
  port: 8025
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8029/eureka/ # this is the address of Eureka server
  instance:
    prefer-ip-address: true
    appname: paymentservice

spring:
  application:
    name: paymentservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  
  datasource:
    url: jdbc:mysql://localhost:3306/busmicroservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
